from core.exceptions.base_core_exception import BaseCoreException


class S3BucketException(BaseCoreException):
    pass
