from core.exceptions.base_core_exception import BaseCoreException


class UnreachableUrlException(BaseCoreException):
    pass
